FROM python:3.10-slim

WORKDIR /app

COPY DAGs/google_cloud/transform/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install flask gunicorn pyarrow

COPY DAGs/google_cloud/transform/ .

ENV PORT=8080
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 main:app