# -*- coding: utf-8 -*-
"""api_calls.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXwuyMiugXf2GalZi7cD9wYG-qjkmssa
"""

import requests

# 🏋️ Wger API call
def get_exercises():
    url = "https://wger.de/api/v2/exerciseinfo/?language=2"
    response = requests.get(url)
    return response.json()

# 🍎 Nutritionix API call
def get_nutrition_data(food_query, app_id, app_key):
    url = "https://trackapi.nutritionix.com/v2/natural/nutrients"
    headers = {
        "x-app-id": app_id,
        "x-app-key": app_key,
        "x-remote-user-id": "0"
    }
    data = {"query": food_query}
    response = requests.post(url, json=data, headers=headers)
    return response.json()

# 🌤️ OpenWeatherMap API call
def get_weather_data(city_name, api_key):
    url = "http://api.openweathermap.org/data/2.5/weather"
    params = {"q": city_name, "appid": api_key, "units": "metric"}
    response = requests.get(url, params=params)
    return response.json()

# Example test calls (fill in your actual keys/values)
if __name__ == "__main__":
    exercises_data = get_exercises()
    print("Exercises Data:", exercises_data)

    nutrition_data = get_nutrition_data("1 apple", "e7b7f0e3", "8e91f72ee33e592081b047ce15ebdb11")
    print("Nutrition Data:", nutrition_data)

    weather_data = get_weather_data("College Park", "cc39e55645488541724622e038d6a2c3")
    print("Weather Data:", weather_data)